import '@/styles/globals.css'
import type { Metadata } from 'next'
import { headers } from 'next/headers'
import { type ReactNode } from 'react'
import { cookieToInitialState } from 'wagmi'

import { getConfig } from '../wagmi'
import { Providers } from './providers'
import { Header } from '@/components/layout/Header'

export const metadata: Metadata = {
  title: 'Create Wagmi',
  description: 'Generated by create-wagmi',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  const initialState = cookieToInitialState(
    getConfig(),
    headers().get('cookie')
  )

  return (
    <html lang="en">
      <body>
        <Providers initialState={initialState}>
          <Header />
          <main className="pt-16">{children}</main>
        </Providers>
      </body>
    </html>
  )
}
